### ISSUE TITLE
cute_sound.h - C2362 error

### ISSUE THREAD

**Issue by PcChip** [RandyGaul/cute_headers#104] opened 2018-07-09 07:26 UTC
Hi,

I'm sure this is a silly error on my part, but when following the examples to try to get cute_sound up and running, my Visual Studio 2017 complains that the 'goto ts_err' is skiping initialization of many variables  
  
I have it included exactly as so:  

// only create header symbols
#define STB_VORBIS_HEADER_ONLY
#include "stb_vorbis.c"

// create header + implementation
#define CUTE_SOUND_IMPLEMENTATION
#include "cute_sound.h"  
  
how can I resolve this?  
  
also, at the very bottom my main.cpp file I have the following (per the vorbis example)  
// create implementation
#undef STB_VORBIS_HEADER_ONLY
#include "stb_vorbis.c"  
  
and that creates error C2872 - 'int8': ambiguous symbol  - any suggestions on what I can change for that one?  
  
thanks for the awesome libraries!

**Comment by chisaipete** [comment] 2018-07-09 13:43
I recently submitted a pull request to update the cute_tiled.h header which had similar issues. You can get these errors to go away by using compiler flag -fpermissive OR by correcting the issues.  

The issue is that there are goto statements in the execption handling which cause the program execution order to skip initialization statements for some variables. Usually this can be solved by some simple reordering to hoist the variable initialization above the goto statements.  

Does that help?

**Comment by chisaipete** [comment] 2018-07-09 13:45
There are other local solutions, like assigning the variable to it's own local scope explicitly which will correct the issue as well.

**Comment by RandyGaul** [comment] 2018-07-22 18:44
You can try turning off Zc or Za in the compiler settings. These disable some very annoying warnings and errors. If you’d like an example there are some 2017 projects in the examples folder.

Ideally the code can be refactored slightly to avoid these errors. Chisaipete has good suggestions on this.

**Comment by RandyGaul** [comment] 2019-01-14 03:36
Closing this for now. Let me know if you have other questions or need to re-open!

**Closed by RandyGaul** 2019-01-14 03:36 UTC

**Comment by FrankenApps** [comment] 2020-02-25 17:59
I have the same problem with VS2019. Setting the flags 

> Zc or Za

did not help. I will now try to refactor the code.
These are the errors I got:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2362	initialization of 'samples' is skipped by 'goto unlock'	cute_sound_basic	C:\Users\Administrator.MS01\Development\C++\SmallFunctionalProjects\cute_sound_basic\src\cute_sound.h	2465	
Error	C2362	initialization of 'ptr' is skipped by 'goto unlock'	cute_sound_basic	C:\Users\Administrator.MS01\Development\C++\SmallFunctionalProjects\cute_sound_basic\src\cute_sound.h	2465	
Error	C2362	initialization of 'floatB' is skipped by 'goto unlock'	cute_sound_basic	C:\Users\Administrator.MS01\Development\C++\SmallFunctionalProjects\cute_sound_basic\src\cute_sound.h	2465	
Error	C2362	initialization of 'floatA' is skipped by 'goto unlock'	cute_sound_basic	C:\Users\Administrator.MS01\Development\C++\SmallFunctionalProjects\cute_sound_basic\src\cute_sound.h	2465	
Error	C2362	initialization of 'wide_count' is skipped by 'goto unlock'	cute_sound_basic	C:\Users\Administrator.MS01\Development\C++\SmallFunctionalProjects\cute_sound_basic\src\cute_sound.h	2465	
Error	C2362	initialization of 'samples_to_write' is skipped by 'goto unlock'	cute_sound_basic	C:\Users\Administrator.MS01\Development\C++\SmallFunctionalProjects\cute_sound_basic\src\cute_sound.h	2465	
```

As a temporary workaround I moved this statement:
`if (!bytes_to_write) goto unlock;` 
from line **2221** to line **2431** like so:
```
cs_memcpy_to_directsound(ctx, (int16_t*)samples, byte_to_lock, bytes_to_write); //line 2429

if (!bytes_to_write) goto unlock; //line 2431
```
