### ISSUE TITLE
cute_sound.h: Help with SDL2/high-level API?

### ISSUE THREAD

**Issue by fluffrabbit** [RandyGaul/cute_headers#186] opened 2020-04-25 03:25 UTC
As far as I can tell, the library seems to be working as intended, but despite my intimate involvement with it this week, I'm tripping over the basics.

It seems that in this test case, the same sound is playing twice even though I'm asking the library to play two different sounds. The bug(s) herein seem to manifest in multiple ways when testing with Emscripten, but on desktop it's very clearly just the same sound twice.

I leave it to you, Randy. tyvm
[test_highlevel_sdl.zip](https://github.com/RandyGaul/cute_headers/files/4532274/test_highlevel_sdl.zip)

**Comment by RandyGaul** [comment] 2020-04-25 15:24
I’m on mobile majority of today, but if you make it easily readable on mobile I can peek now. Maybe post your main.c here in a comment, or just your own repo and link it here?

**Comment by RandyGaul** [comment] 2020-04-25 15:25
Does not have to be runnable — I’ll debug your .zip file later.

**Comment by fluffrabbit** [comment] 2020-04-25 16:55
You really go the extra mile. Okay, here's the main cpp. Thanks!

```c++
#define CUTE_SOUND_FORCE_SDL
#define CUTE_SOUND_IMPLEMENTATION
#include <cute_sound.h>

#include <iostream>

struct csSound {
	cs_loaded_sound_t data;
	cs_play_sound_def_t def;
};

cs_context_t *csctx;

csSound csLoadSound( std::string fileName ){
	csSound sound;
	sound.data = cs_load_wav( fileName.c_str() );
	sound.def = cs_make_def( &sound.data );
	std::cout << fileName << " has " << sound.data.sample_count << " samples" << std::endl;
	return sound;
}

void csPlaySound( csSound &sound ){
	cs_play_sound( csctx, sound.def );
}

csSound sound_jump, sound_select;

int main(){
	// 4096 samples per window * 2 channels.
	csctx = cs_make_context( nullptr, 48000, 4096 * 2, 5, nullptr );
	sound_jump  = csLoadSound( "jump.wav" );
	sound_select  = csLoadSound( "select.wav" );
	std::cout << "Playing jump.wav" << std::endl;
	csPlaySound( sound_jump );
	int i = 60;
	while( i-- ){
		cs_mix( csctx );
		cs_sleep( 17 );
	}
	std::cout << "Playing select.wav" << std::endl;
	csPlaySound( sound_select );
	i = 60;
	while( i-- ){
		cs_mix( csctx );
		cs_sleep( 17 );
	}
	cs_shutdown_context( csctx );
	return 0;
}
```

**Comment by RandyGaul** [comment] 2020-04-26 04:31
There may be a bug introduced by moving variables to avoid goto skipping constructor problems. This will require debugging. I’ll look into it soon.

**Comment by fluffrabbit** [comment] 2020-04-26 06:58
I'm relieved to tell you that I don't think that's true. I'm testing with a commit prior to my meddling (albeit with rwops functions removed) and I'm hearing the same problem.

I may also be hallucinating, but it almost seems like the sound changes sometimes maybe, so maybe a variable somewhere is default-initialized (declared but not zeroed) and it's picking up random data, making it work properly sometimes but not others. But perhaps not.

**Comment by RandyGaul** [comment] 2020-04-26 07:53
Ah, I see the problem. Try this out real quick. If you like, for fun, you can try and figure out what the problem was. I posted the solution at the bottom of this post :)

```cpp
#define CUTE_SOUND_FORCE_SDL
#define CUTE_SOUND_IMPLEMENTATION
#include <cute_sound.h>

#include <iostream>

cs_context_t *csctx;

cs_loaded_sound_t csLoadSound( std::string fileName ){
	cs_loaded_sound_t loaded_sound;
	loaded_sound = cs_load_wav( fileName.c_str() );
	std::cout << fileName << " has " << loaded_sound.sample_count << " samples" << std::endl;
	return loaded_sound;
}

void csPlaySound( cs_loaded_sound_t& loaded_sound ){
	// Just use default parameters for the def.
	cs_play_sound_def_t def = cs_make_def( &loaded_sound );
	cs_play_sound( csctx, def );
}

cs_loaded_sound_t sound_jump, sound_select;

int main(){
	// 4096 samples per window * 2 channels.
	csctx = cs_make_context( nullptr, 44100, 8192, 5, nullptr );
	sound_jump  = csLoadSound( "jump.wav" );
	sound_select  = csLoadSound( "select.wav" );
	cs_spawn_mix_thread( csctx );

	std::cout << "Playing jump.wav" << std::endl;
	csPlaySound( sound_jump );
	cs_sleep( 2000 );

	std::cout << "Playing select.wav" << std::endl;
	csPlaySound( sound_select );
	cs_sleep( 2000 );

	cs_shutdown_context( csctx );
	return 0;
}
```

---

SOLUTION

The memory for the loaded sound is referenced in a playing sound definition by pointer. This means that once a sound is loaded into memory, the `cs_loaded_sound_t` instance has to stay in memory and not move. Def structs (short for definition) are intended to be short-lived and not persist. They simply pass a lot of parameters to the `cs_play_sound` function.

I could have instead designed the API so that `cs_play_sound` takes lots of individual parameters. However, this does not scale very well into the future, as whenever I want to add new parameters or change their ordering it would break old code. Instead, a parameter struct makes it easier to maintain the API over time.

I noticed that you had been storing your loaded sound on stack like so.

```cpp
csSound csLoadSound( std::string fileName ){
	csSound sound; // <-- STORED ON THE STACK
	sound.data = cs_load_wav( fileName.c_str() );
	sound.def = cs_make_def( &sound.data );
	std::cout << fileName << " has " << sound.data.sample_count << " samples" << std::endl;
	return sound;
}
```

The def struct now points to the struct on the stack. Your code will still likely run most of the time, since this stack memory will likely go uncorrupted for the most part. However, once you call `csLoadSound` again that same location on the stack will be overwritten by a new instance, particularly your second audio file loaded into memory. So later on both of your `csSound` instances will be pointing to the same `cs_loaded_sound_t` memory on the stack, and both play the same audio.

If you'd like to wrap the cute sound structs inside of your own structs or classes, that is perfectly fine, but be extra careful about the lifetime of the def struct.

**Comment by RandyGaul** [comment] 2020-04-26 08:02
If you want to define your own sound data type, here is my recommendation, something like this example. Store all the parameters you like in your own data type, and pass them along to the def struct briefly.

```cpp
#define CUTE_SOUND_FORCE_SDL
#define CUTE_SOUND_IMPLEMENTATION
#include <cute_sound.h>

#include <iostream>

cs_context_t *csctx;

struct sound_t
{
	cs_loaded_sound_t audio_source;
	bool loop = false;
	float volume = 1.0f;
};

sound_t load_sound( std::string fileName ){
	cs_loaded_sound_t loaded_sound;
	loaded_sound = cs_load_wav( fileName.c_str() );
	std::cout << fileName << " has " << loaded_sound.sample_count << " samples" << std::endl;
	sound_t sound;
	sound.audio_source = loaded_sound;
	return sound;
}

void play_sound( sound_t sound ){
	cs_play_sound_def_t def = cs_make_def( &sound.audio_source );
	def.looped = (int)sound.loop;
	def.volume_left = sound.volume;
	def.volume_right = sound.volume;
	cs_play_sound( csctx, def );
}

sound_t sound_jump, sound_select;

int main(){
	// 4096 samples per window * 2 channels.
	csctx = cs_make_context( nullptr , 44100, 8192, 5, nullptr );
	sound_jump  = load_sound( "jump.wav" );
	sound_select  = load_sound( "select.wav" );
	cs_spawn_mix_thread( csctx );

	std::cout << "Playing jump.wav" << std::endl;
	play_sound( sound_jump );
	cs_sleep( 2000 );

	std::cout << "Playing select.wav" << std::endl;
	play_sound( sound_select );
	cs_sleep( 2000 );

	cs_shutdown_context( csctx );
	return 0;
}
```

**Comment by RandyGaul** [comment] 2020-04-26 08:04
And finally, I do recommend logging the `sample_rate` (see `cs_loaded_sound_t::sample_rate`) of your loaded audio just to ensure you setup the cute_sound context and create your audio with matching sample rates.

**Comment by fluffrabbit** [comment] 2020-04-26 08:07
Regarding sample rate, I am well aware of the problem and would recommend a compact quick-and-dirty resampling implementation. I can make one myself, though it won't be SIMD and definitely won't be high-quality.

Your explanation makes sense, though I'm not sure I understand the logic about def pointers. I guess just making the defs before each call is a good solution, and obviates the need to store multiple objects per sound. In the Vulkan API, AFAIK parameters are put in as POD structs. Any reason defs aren't PODs?

**Comment by RandyGaul** [comment] 2020-04-26 08:11
The problem is that `cs_loaded_sound_t` isn't POD -- it is storing a pointer to the loaded audio.

Alternatively I could change the def struct to copy the *entire* `cs_loaded_sound_t` struct inside of itself, then there'd by absolutely no problem. Actually... I think this makes a superior API, and nobody else could accidentally make the same bug you did. Let me try this out real quick.

**Comment by RandyGaul** [comment] 2020-04-26 08:13
Also, if you make a resampling function please post it. I would love to have a function that takes a `cs_loaded_sound_t` struct and returns a new one with resampling done. If you implement this feature I would happily alter it to add SSE.

**Comment by fluffrabbit** [comment] 2020-04-26 08:14
>Alternatively I could change the def struct to copy the entire cs_loaded_sound_t struct inside of itself, then there'd by absolutely no problem. Actually... I think this makes a superior API, and nobody else could accidentally make the same bug you did.

Copying 30 MB of data might not be a great idea.

>Also, if you make a resampling function please post it. I would love to have a function that takes a cs_loaded_sound_t struct and returns a new one with resampling done. If you implement this feature I would happily alter it to add SSE.

Adding it to the list.

**Comment by RandyGaul** [comment] 2020-04-26 08:18
It wouldn't copy the audio itself, just the struct referencing the audio.

But, I see the problem. This would require that every single playing sound instance also store the `cs_loaded_sound_t` struct, which is pretty annoying. I think it's probably simpler to keep it as-is. I added a small note in the docs about the problem you ran into.

**Comment by fluffrabbit** [comment] 2020-04-26 08:20
>It wouldn't copy the audio itself, just the struct referencing the audio.

I didn't know there was a difference. This padawan has much to learn.

>But, I see the problem. This would require that every single playing sound instance also store the cs_loaded_sound_t struct, which is pretty annoying.

Storing a struct within a struct is annoying? Okay, I'll take your word for it.

>I added a small note in the docs about the problem you ran into.

Thanks!

**Comment by RandyGaul** [comment] 2020-04-26 08:26
> Storing a struct within a struct is annoying? Okay, I'll take your word for it.

You definitely don't need to worry about all this discussion if you don't care -- I'm just posting it here since the discussion is helpful for me personally, and in case you're curious!

The problem isn't that it's a struct within a struct. The problem here is the lifetime of `cs_loaded_sound_t` goes from "whatever the user does", to something way more complicated. It starts getting copied around everywhere.

So two options:
1. All playing audio instances have a pointer to a single `cs_loaded_audio_t` struct.
2. All playing audio instances copy a user-provided `cs_loaded_audio_t` into themselves.

Option 2 does make debugging quite a bit harder.

```cpp
void cs_free_sound(cs_loaded_sound_t* sound)
{
	cs_free16(sound->channels[0], NULL);
	memset(sound, 0, sizeof(cs_loaded_sound_t));
}
```

Since this function clears the pointer to the audio itself `cs_mix` will actually assert on this condition with a really helpful error message.

```cpp
// Attempted to play a sound with no audio.
// Make sure the audio file was loaded properly. Check for
// error messages in cs_error_reason.
CUTE_SOUND_ASSERT(cA);
```

But, if all the individual playing sound instances store individual copies of the `cs_playing_sound_t` struct then it's not possible to have an assert like this here, and instead the entire program will reference a pointer to free'd audio memory and then likely crash, or maybe even worse since it's undefined behavior.

**Comment by fluffrabbit** [comment] 2020-04-26 08:36
>You definitely don't need to worry about all this discussion if you don't care

I'm definitely interested. I attempted to make my own audio library as a replacement for SDL_mixer, but the bugs caught up to me and it became a rather miserable affair.

>All playing audio instances have a pointer to a single cs_loaded_audio_t struct. This is what cute_sound currently does.

Sounds rational.

>Option 2 does make debugging quite a bit harder.

I can see from your memory-aligned magic that this is the case.

Would it be reasonable to have a pre-allocated memory pool in which sounds are permanently stored? I'm talking a big array of samples, or a global linked list of dynamically allocated (`alloca` or `malloc` I don't care) pieces of sound. Maybe as a member of ctx.

**Comment by RandyGaul** [comment] 2020-04-27 09:46
Memory pool could be done, but as far as API goes it wouldn't really give any improvements here, at least not that I can think of.

Closing this out! Feel free to re-open or comment more if needed :)

**Closed by RandyGaul** 2020-04-27 09:46 UTC

**Comment by fluffrabbit** [comment] 2020-04-27 18:33
Though it's not really necessary, a memory pool would keep the samples and important metadata stationary so that long-lived pointers could replace the stack-based system that currently exists behind the scenes, without the overhead of copying large chunks of data.

**Comment by RandyGaul** [comment] 2020-04-27 20:28
The system isn’t necessarily stack based. It’s entirely up to the user how they store instances of loaded sounds.

I could write code to store loaded sound instances on the heap, but right now I’m leaving that up to the user to figure out how they want to do so. Usually people will store the loaded sound structs in a hash table.

If I implement a memory pool then I have to worry about how to deal with freeing up old loaded sounds and adding new ones over time, and then communicate all these details to the user over the API. In my opinion a superior API is one that needs to communicate less details. This is all a cost benefit analysis. What are the benefits of adding in a memory pool, and what are the costs? There are more costs I haven’t mentioned yet, such as having more code means more chances for bugs, more docs to write and maintain, more code to maintain, more time sunk into development. The mere existence of more code should bring really strong and clear benefits that definitely outweigh the costs.

**Comment by fluffrabbit** [comment] 2020-04-27 23:46
The "more code" argument is sound, and I think that the user owning 
memory is reasonable. I just wouldn't rule anything out considering the 
concept of a "def" and how it is used is odd API design. I love this 
library; it works. However, there is a learning curve.

**Comment by RandyGaul** [comment] 2020-04-28 00:37
I agree with you! I'm just struggling to find a better way... It is a bit silly that a def points to an loaded audio instance, and that instance has to *persist*.

But I justify it in my head by thinking that cute_sound is a fairly low level library. But I honestly think that's kind of a cop-out.

Maybe if I use cute_sound more myself I will come to a better idea.

**Comment by fluffrabbit** [comment] 2020-04-28 04:54
It's not silly that audio data has to persist, just that a def is created with a function while encapsulating a very small amount of data. But it's also kind of interesting. For instance, you could easily create a cheap reverb effect by playing a few sounds with varying delay and volume. Changing volume based on listener position would complicate things though, and then you're changing the state of playing sounds, which is hard for me to imagine.
